#!/bin/sh
~/Documents/iac/lab0-devtools/tools/attach_usb.sh
# cleanup
rm -rf obj_dir
rm -f counter.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace clktick.sv f1_fsm.sv f1_lights.sv --exe clktick_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vclktick.mk Vclktick


# run executable simulation file
obj_dir/Vclktick
